package com.ecommerce.computerequipmentsales.constants;

public enum BusinessRule {

    COMPUTER_CASE_NOT_FOUND("COMPUTER_CASE_NOT_FOUND"),
    COMPUTER_CASE_PSU_NOT_FOUND("COMPUTER_CASE_PSU_NOT_FOUND"),
    DISPLAY_CARD_NOT_FOUND("DISPLAY_CARD_NOT_FOUND"),
    DISPLAY_CARD_GPU_NOT_FOUND("DISPLAY_CARD_GPU_NOT_FOUND"),
    DISPLAY_CARD_MEMORY_NOT_FOUND("DISPLAY_CARD_MEMORY_NOT_FOUND"),
    HDD_NOT_FOUND("HDD_NOT_FOUND"),
    LAPTOP_NOT_FOUND("LAPTOP_NOT_FOUND"),
    LAPTOP_SCREEN_NOT_FOUND("LAPTOP_SCREEN_NOT_FOUND"),
    LAPTOP_SSD_NOT_FOUND("LAPTOP_SSD_NOT_FOUND"),
    LAPTOP_HDD_NOT_FOUND("LAPTOP_HDD_NOT_FOUND"),
    LAPTOP_GPU_NOT_FOUND("LAPTOP_GPU_NOT_FOUND"),
    LAPTOP_PROCESSOR_NOT_FOUND("LAPTOP_PROCESSOR_NOT_FOUND"),
    LAPTOP_RAM_NOT_FOUND("LAPTOP_RAM_NOT_FOUND"),
    MAINBOARD_NOT_FOUND("MAINBOARD_NOT_FOUND"),
    MAINBOARD_RAM_NOT_FOUND("MAINBOARD_RAM_NOT_FOUND"),
    MONITOR_NOT_FOUND("MONITOR_NOT_FOUND"),
    MONITOR_SCREEN_NOT_FOUND("MONITOR_SCREEN_NOT_FOUND"),
    PROCESSOR_NOT_FOUND("PROCESSOR_NOT_FOUND"),
    PROCESSOR_CORE_NOT_FOUND("PROCESSOR_CORE_NOT_FOUND"),
    RAM_NOT_FOUND("RAM_NOT_FOUND"),
    SSD_NOT_FOUND("SSD_NOT_FOUND"),
    STOCK_NOT_FOUND("STOCK_NOT_FOUND"),
    PRODUCT_CODE_IS_USING("PRODUCT_CODE_IS_USING");

    BusinessRule(String description){
        this.description = description;
    };

    private final String description;

    public String getDescription() {
        return this.description;
    }
}
